### ISSUE TITLE
run_cluster_gcn_notebook.ipynb requires kernel restart

### ISSUE THREAD

**Issue by nmb-paperspace** [gradient-ai/Graphcore-Tensorflow2#22]
`run_cluster_gcn_notebook.ipynb` doesn't work with "Run All" on first time through. The kernel has to be restarted after the pip installs before it will go through (~ none of the other notebooks require this).

**Comment by nmb-paperspace** [comment]
If restart required good to highlight to user (not just pip's output)

**Comment by payoto** [comment]
I think this might be linked to an outage/degraded performance at Canonical, we rely on the Ubuntu archives to install overlayfs and use it to symlink the datasets into writable directories.
Because of this outage if I run through the notebook too fast after starting the session I get errors around the datasets, if I wait for the setup to finish (when the message `Finished running setup.sh` appears in the log I don't see that error).

I think it might be worth retrying in a few hours see if the error persists or not

**Comment by nmb-paperspace** [comment]
OK I reran this, waiting for `Finished running setup.sh`, and it went through firs time on Run All, so we can close this
